import { LocationData } from '../types';

export const DEMO_LOCATIONS: LocationData[] = [
  {
    id: 'mangalagiri-ap',
    name: 'Mangalagiri (Rural Panchayat)',
    block: 'Mangalagiri Block / Mandal',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    pinCode: '522503',
    regionType: 'Peri-Urban & Rural Weavers / Agri Cluster',
    marketReachKm: 7.5,
    nearbyPopulation: 24800,
    totalHouseholds: 5600,
    avgMonthlyHouseholdIncome: 17500,
    dairyCompetitorCount: 4,
    groceryCompetitorCount: 9,
    tailoringCompetitorCount: 6,
    poultryCompetitorCount: 3,
    foodProcessingCompetitorCount: 2,
    otherCompetitorCount: 5,
    dairyDemandLpd: 1850, // Litres per day within 7.5km
    groceryDailySpendEstimate: 215000, // Daily grocery spend in catchment
    centerCoords: { lat: 16.4346, lng: 80.5663 },
    dairyCompetitors: [
      {
        id: 'comp-d1',
        name: 'Sangam Milk Chilling Center',
        type: 'cooperative_hub',
        distanceKm: 3.2,
        directionAngleDeg: 45,
        details: 'Cooperative procurement hub; offers ₹48-52/L to farmers for buffalo milk.',
        impactLevel: 'Medium',
        dailyVolume: '850 L/day',
      },
      {
        id: 'comp-d2',
        name: 'Venkata Dairy Farm (Atmakur)',
        type: 'competitor',
        distanceKm: 5.4,
        directionAngleDeg: 130,
        details: 'Private 12-cow dairy farm supplying bulk milk to nearby sweet shops.',
        impactLevel: 'Medium',
        dailyVolume: '220 L/day',
      },
      {
        id: 'comp-d3',
        name: 'Koppuravuru Village Collection Point',
        type: 'cooperative_hub',
        distanceKm: 6.8,
        directionAngleDeg: 210,
        details: 'Government SHG collection unit with basic FAT/SNF testing.',
        impactLevel: 'Low',
        dailyVolume: '410 L/day',
      },
      {
        id: 'comp-d4',
        name: 'Sri Krishna Dairy Parlour',
        type: 'competitor',
        distanceKm: 2.1,
        directionAngleDeg: 315,
        details: 'Direct retail booth selling packaged pouch milk & curd.',
        impactLevel: 'High',
        dailyVolume: '350 L/day',
      },
      {
        id: 'dem-d1',
        name: 'Nidamarru Temple & School Hamlet',
        type: 'unserved_hamlet',
        distanceKm: 4.8,
        directionAngleDeg: 90,
        details: 'High unmet daily demand for fresh unadulterated cow/buffalo milk & paneer.',
        impactLevel: 'High',
        dailyVolume: '320 L/day unmet',
      },
      {
        id: 'dem-d2',
        name: 'Mangalagiri Weaver Colony Anchor Demand',
        type: 'anchor_demand',
        distanceKm: 1.8,
        directionAngleDeg: 270,
        details: 'Dense handloom artisan cluster (850 households) preferring direct doorstep milk delivery.',
        impactLevel: 'High',
        dailyVolume: '600 L/day demand',
      },
    ],
    groceryCompetitors: [
      {
        id: 'comp-g1',
        name: 'Lakshmi Kirana & General Store',
        type: 'competitor',
        distanceKm: 0.8,
        directionAngleDeg: 20,
        details: 'Established 15-year old dry ration shop near market chowk with loyal credit customers.',
        impactLevel: 'High',
        dailyVolume: '₹28,000/day',
      },
      {
        id: 'comp-g2',
        name: 'Balaji Super Bazaar Mini',
        type: 'competitor',
        distanceKm: 2.4,
        directionAngleDeg: 85,
        details: 'Semi-modern self-service format with branded FMCG and packaged snacks.',
        impactLevel: 'High',
        dailyVolume: '₹35,000/day',
      },
      {
        id: 'comp-g3',
        name: 'Srinivasa Rice Depot',
        type: 'competitor',
        distanceKm: 1.5,
        directionAngleDeg: 190,
        details: 'Specializes in bulk Sonamasuri & BPT rice bags direct from Tenali mills.',
        impactLevel: 'Medium',
        dailyVolume: '₹18,000/day',
      },
      {
        id: 'comp-g4',
        name: 'Gramin Rythu Provisional Store',
        type: 'competitor',
        distanceKm: 4.2,
        directionAngleDeg: 260,
        details: 'Basic village store with oils, pulses, matches, soaps and loose spices.',
        impactLevel: 'Low',
        dailyVolume: '₹9,500/day',
      },
      {
        id: 'dem-g1',
        name: 'Navodaya Nagar Residential Extension',
        type: 'unserved_hamlet',
        distanceKm: 3.6,
        directionAngleDeg: 140,
        details: 'New housing zone (420 households) currently travelling 3.5km for daily provisions.',
        impactLevel: 'High',
        dailyVolume: '₹45,000/day potential',
      },
    ],
    tailoringCompetitors: [
      {
        id: 'comp-t1',
        name: 'Padmavathi Handloom Tailoring & Blouse Works',
        type: 'competitor',
        distanceKm: 1.2,
        directionAngleDeg: 35,
        details: 'Specializes in bridal saree pico-falls, blouse embroidery and school uniforms.',
        impactLevel: 'High',
        dailyVolume: '15 orders/day',
      },
      {
        id: 'comp-t2',
        name: 'Sri Sai Men & Kids Tailors',
        type: 'competitor',
        distanceKm: 2.7,
        directionAngleDeg: 160,
        details: 'Gents shirts, trousers and traditional dhoti-kurta stitching.',
        impactLevel: 'Medium',
        dailyVolume: '8 orders/day',
      },
      {
        id: 'dem-t1',
        name: 'Kothapet Weaver Cooperative Colony',
        type: 'anchor_demand',
        distanceKm: 2.0,
        directionAngleDeg: 290,
        details: 'High steady demand for fast garment finishing and boutique designer stitching.',
        impactLevel: 'High',
        dailyVolume: '25 orders/day unmet',
      },
    ],
    poultryCompetitors: [
      {
        id: 'comp-p1',
        name: 'Andhra Broiler Commercial Farm',
        type: 'competitor',
        distanceKm: 4.5,
        directionAngleDeg: 55,
        details: 'Contract farming broiler shed (4,000 birds batch).',
        impactLevel: 'High',
        dailyVolume: '120 birds/day',
      },
      {
        id: 'dem-p1',
        name: 'Mangalagiri Highway Dhaba & Eateries Corridor',
        type: 'anchor_demand',
        distanceKm: 3.1,
        directionAngleDeg: 230,
        details: 'Strong daily wholesale demand for farm fresh broiler chicken and country eggs (Natukodi).',
        impactLevel: 'High',
        dailyVolume: '180 kg/day demand',
      },
    ],
    foodProcessingCompetitors: [
      {
        id: 'comp-fp1',
        name: 'Annapurna Spices & Pickles Micro Unit',
        type: 'competitor',
        distanceKm: 2.2,
        directionAngleDeg: 75,
        details: 'Local Guntur chilli powder processing and mango/lemon pickle packaging.',
        impactLevel: 'Medium',
        dailyVolume: '60 kg/day',
      },
      {
        id: 'dem-fp1',
        name: 'Weekly Rythu Santha & Temple Tourist Stalls',
        type: 'anchor_demand',
        distanceKm: 1.5,
        directionAngleDeg: 340,
        details: 'Unmet demand for hygienically packed cold-pressed sesame oil, ready spice mixes and millet snacks.',
        impactLevel: 'High',
        dailyVolume: '₹15,000/day potential',
      },
    ],
    otherCompetitors: [
      {
        id: 'comp-oth1',
        name: 'Gramin Agro Service & Rural Enterprise Hub',
        type: 'competitor',
        distanceKm: 1.9,
        directionAngleDeg: 120,
        details: 'Multi-service rural equipment rental and maintenance center.',
        impactLevel: 'Medium',
        dailyVolume: '12 visits/day',
      },
    ],
    dairySpecificThreats: [
      {
        title: 'Summer Green Fodder Scarcity',
        severity: 'Medium',
        mitigation: 'Tie up with local canal farmers for silage bags and cultivate hybrid Napier grass on 0.5 acre lease.',
      },
      {
        title: 'Cold Storage Spoilage during Power Cut',
        severity: 'High',
        mitigation: 'Include solar-powered 300L bulk milk cooler or battery inverter chiller in project cost equipment.',
      },
      {
        title: 'Bovine Health & Mastitis Risk',
        severity: 'Medium',
        mitigation: 'Mandatory livestock insurance (covered under PM Rashtriya Gokul Mission) & veterinary tie-up at Mangalagiri clinic.',
      },
    ],
    grocerySpecificThreats: [
      {
        title: 'Working Capital Lockup in Village Credit (Udhaari)',
        severity: 'High',
        mitigation: 'Implement digital ledger (Khata app) with a strict ₹1,000 ceiling per household and 15-day settlement cycle.',
      },
      {
        title: 'Wholesale Price Fluctuation in Pulses & Edible Oil',
        severity: 'Medium',
        mitigation: 'Procure bi-weekly from Vijayawada Kaleswara Rao wholesale market to minimize holding risk.',
      },
      {
        title: 'Inventory Expiry / Pest Damage',
        severity: 'Low',
        mitigation: 'Adopt FIFO inventory rotation and modern metal shelving bins off the ground.',
      },
    ],
    tailoringSpecificThreats: [
      {
        title: 'Machine Breakdown during Festival Peak Season',
        severity: 'Medium',
        mitigation: 'Maintain annual maintenance contract with Vijayawada sewing technician and keep spare motor belts.',
      },
      {
        title: 'Fabric Raw Material Price Inflation',
        severity: 'Low',
        mitigation: 'Procure threads, buttons, and linings in bulk directly from Mangalagiri weaver wholesale societies.',
      },
    ],
    poultrySpecificThreats: [
      {
        title: 'Feed Cost Spike (Maize & Soya Meal)',
        severity: 'High',
        mitigation: 'Form local purchase consortium with neighboring poultry growers for direct mill rate procurement.',
      },
      {
        title: 'Bird Mortality and Heat Stress in Summer',
        severity: 'High',
        mitigation: 'Install foggers, exhaust fans, and strictly follow biosecurity vaccination calendars.',
      },
    ],
    foodProcessingSpecificThreats: [
      {
        title: 'Raw Material Seasonality & Crop Price Volatility',
        severity: 'Medium',
        mitigation: 'Contract harvest-season buying with Guntur Mirchi Yard farmers and utilize dry warehouse storage.',
      },
      {
        title: 'FSSAI Packaging & Shelf-life Compliance',
        severity: 'Low',
        mitigation: 'Adopt nitrogen-flushed pouch sealing and clean batch labeling with expiry tracking.',
      },
    ],
    otherSpecificThreats: [
      {
        title: 'Demand Fluctuation in Monsoon Months',
        severity: 'Medium',
        mitigation: 'Maintain 3 months emergency operating liquidity reserve.',
      },
    ],
  },
  {
    id: 'anand-gj',
    name: 'Anand (Ode Village Cluster)',
    block: 'Anand Taluka Block',
    district: 'Anand',
    state: 'Gujarat',
    pinCode: '388200',
    regionType: 'Cooperative Heartland & High-Yield Dairy Zone',
    marketReachKm: 8.0,
    nearbyPopulation: 31200,
    totalHouseholds: 6800,
    avgMonthlyHouseholdIncome: 22000,
    dairyCompetitorCount: 6,
    groceryCompetitorCount: 11,
    tailoringCompetitorCount: 7,
    poultryCompetitorCount: 4,
    foodProcessingCompetitorCount: 3,
    otherCompetitorCount: 6,
    dairyDemandLpd: 3200,
    groceryDailySpendEstimate: 290000,
    centerCoords: { lat: 22.5645, lng: 72.9289 },
    dairyCompetitors: [
      {
        id: 'an-d1',
        name: 'Amul Village Cooperative Society (Ode)',
        type: 'cooperative_hub',
        distanceKm: 1.2,
        directionAngleDeg: 30,
        details: 'Automated milk collection system with instant digital fat/protein slip payout.',
        impactLevel: 'High',
        dailyVolume: '1400 L/day',
      },
      {
        id: 'an-d2',
        name: 'Patel Dairy & Cattle Breeding Center',
        type: 'competitor',
        distanceKm: 4.5,
        directionAngleDeg: 150,
        details: 'Mehsani buffalo specialist producing high-fat mawa and paneer.',
        impactLevel: 'Medium',
        dailyVolume: '380 L/day',
      },
      {
        id: 'an-dem1',
        name: 'Industrial Corridor Colony Hub',
        type: 'anchor_demand',
        distanceKm: 5.1,
        directionAngleDeg: 280,
        details: 'High premium demand for A2 Gir cow milk bottles @ ₹75/L.',
        impactLevel: 'High',
        dailyVolume: '450 L/day',
      },
    ],
    groceryCompetitors: [
      {
        id: 'an-g1',
        name: 'Jalaram Provision Store',
        type: 'competitor',
        distanceKm: 1.1,
        directionAngleDeg: 50,
        details: 'Large grocery supplier catering to local village catering & weddings.',
        impactLevel: 'High',
        dailyVolume: '₹42,000/day',
      },
      {
        id: 'an-g2',
        name: 'Shreeji Kirana Mart',
        type: 'competitor',
        distanceKm: 2.8,
        directionAngleDeg: 200,
        details: 'Standard rural convenience store with spices and oils.',
        impactLevel: 'Medium',
        dailyVolume: '₹16,000/day',
      },
    ],
    dairySpecificThreats: [
      {
        title: 'Intense Competition from Established Cooperative',
        severity: 'High',
        mitigation: 'Differentiate with direct-to-consumer value-added products (Paneer, Ghee, Shrikhand) rather than raw milk bulk sale.',
      },
      {
        title: 'High Feed & Concentrate Costs',
        severity: 'Medium',
        mitigation: 'Bulk procurement of cotton-seed cake through local FPO collective bargaining.',
      },
    ],
    grocerySpecificThreats: [
      {
        title: 'Direct Competition from Mini Supermarkets on Highway',
        severity: 'Medium',
        mitigation: 'Focus on village-tailored micro-packs (₹5, ₹10, ₹20 SKUs) and doorstep delivery for elderly patrons.',
      },
    ],
  },
  {
    id: 'baramati-mh',
    name: 'Baramati (Malegaon Bk)',
    block: 'Baramati Tehsil Block',
    district: 'Pune',
    state: 'Maharashtra',
    pinCode: '413115',
    regionType: 'Sugar-Belt & Agri-Tourism Hub',
    marketReachKm: 9.0,
    nearbyPopulation: 28500,
    totalHouseholds: 6100,
    avgMonthlyHouseholdIncome: 20500,
    dairyCompetitorCount: 5,
    groceryCompetitorCount: 8,
    dairyDemandLpd: 2600,
    groceryDailySpendEstimate: 260000,
    centerCoords: { lat: 18.1517, lng: 74.5772 },
    dairyCompetitors: [
      {
        id: 'bm-d1',
        name: 'Malegaon Sahakari Dudh Utpadak Sanstha',
        type: 'cooperative_hub',
        distanceKm: 2.1,
        directionAngleDeg: 60,
        details: 'Cooperative collection unit tied to Mahanand Dairy.',
        impactLevel: 'Medium',
        dailyVolume: '900 L/day',
      },
      {
        id: 'bm-dem1',
        name: 'MIDC Residential Colony',
        type: 'anchor_demand',
        distanceKm: 4.8,
        directionAngleDeg: 320,
        details: 'Daily requirement of 500+ litres of curd & packaged paneer.',
        impactLevel: 'High',
        dailyVolume: '500 L/day',
      },
    ],
    groceryCompetitors: [
      {
        id: 'bm-g1',
        name: 'Samarth Kirana Stores',
        type: 'competitor',
        distanceKm: 1.4,
        directionAngleDeg: 110,
        details: 'Major staple supplier for sugarcane workers and tractor owners.',
        impactLevel: 'High',
        dailyVolume: '₹31,000/day',
      },
    ],
    dairySpecificThreats: [
      {
        title: 'Seasonal Milk Price Drops in Flush Season (Winter)',
        severity: 'Medium',
        mitigation: 'Convert surplus flush milk into long shelf-life Ghee and indigenous butter.',
      },
    ],
    grocerySpecificThreats: [
      {
        title: 'Sugarcane Harvest Seasonal Cashflow Swings',
        severity: 'High',
        mitigation: 'Build cash reserves during peak crushing season (Nov-March) to sustain monsoon lull.',
      },
    ],
  },
  {
    id: 'dharmapuri-tn',
    name: 'Dharmapuri (Palacode Belt)',
    block: 'Palacode Union Block',
    district: 'Dharmapuri',
    state: 'Tamil Nadu',
    pinCode: '636808',
    regionType: 'Dryland Horticulture & Livestock Zone',
    marketReachKm: 7.0,
    nearbyPopulation: 19500,
    totalHouseholds: 4400,
    avgMonthlyHouseholdIncome: 14500,
    dairyCompetitorCount: 3,
    groceryCompetitorCount: 7,
    dairyDemandLpd: 1550,
    groceryDailySpendEstimate: 165000,
    centerCoords: { lat: 12.1211, lng: 78.1582 },
    dairyCompetitors: [
      {
        id: 'dp-d1',
        name: 'Aavin Primary Milk Producers Society',
        type: 'cooperative_hub',
        distanceKm: 2.5,
        directionAngleDeg: 80,
        details: 'Official state cooperative collection center.',
        impactLevel: 'Medium',
        dailyVolume: '620 L/day',
      },
      {
        id: 'dp-dem1',
        name: 'Palacode Market Junction',
        type: 'anchor_demand',
        distanceKm: 3.5,
        directionAngleDeg: 190,
        details: 'High demand for fresh ghee & buttermilk packets during temple festivals.',
        impactLevel: 'High',
        dailyVolume: '280 L/day',
      },
    ],
    groceryCompetitors: [
      {
        id: 'dp-g1',
        name: 'Murugan Maligai Kadai',
        type: 'competitor',
        distanceKm: 0.9,
        directionAngleDeg: 40,
        details: 'Leading village ration and condiment shop.',
        impactLevel: 'High',
        dailyVolume: '₹22,000/day',
      },
    ],
    dairySpecificThreats: [
      {
        title: 'Water Scarcity in Pre-Monsoon Months',
        severity: 'High',
        mitigation: 'Construct small farm pond / rainwater sump and install drip hydroponic maize fodder tray.',
      },
    ],
    grocerySpecificThreats: [
      {
        title: 'Lower Average Transaction Size',
        severity: 'Medium',
        mitigation: 'Stock affordable regional brands and loose sachet offerings.',
      },
    ],
  },
];

export function createCustomLocation(
  village: string,
  block: string,
  district: string,
  state: string
): LocationData {
  const vName = village.trim() || 'Custom Location';
  const bName = block.trim() || `${vName} Block`;
  const dName = district.trim() || 'Local District';
  const sName = state.trim() || 'India';

  return {
    id: `custom-${Date.now()}`,
    name: vName,
    block: bName,
    district: dName,
    state: sName,
    pinCode: '000000',
    regionType: 'Custom Rural / Semi-Urban Panchayat Cluster',
    marketReachKm: 7.0,
    nearbyPopulation: 22000,
    totalHouseholds: 4900,
    avgMonthlyHouseholdIncome: 16000,
    dairyCompetitorCount: 4,
    groceryCompetitorCount: 8,
    tailoringCompetitorCount: 5,
    poultryCompetitorCount: 3,
    foodProcessingCompetitorCount: 2,
    otherCompetitorCount: 4,
    dairyDemandLpd: 1700,
    groceryDailySpendEstimate: 190000,
    centerCoords: { lat: 20.5937, lng: 78.9629 },
    dairyCompetitors: [
      {
        id: 'c-d1',
        name: `${dName} Milk Producers Cooperative Hub`,
        type: 'cooperative_hub',
        distanceKm: 2.8,
        directionAngleDeg: 50,
        details: 'Primary dairy procurement collection center with basic testing.',
        impactLevel: 'Medium',
        dailyVolume: '700 L/day',
      },
      {
        id: 'c-d2',
        name: `${vName} Local Dairy Producer`,
        type: 'competitor',
        distanceKm: 4.2,
        directionAngleDeg: 140,
        details: 'Local 8-10 cattle dairy supplying morning tea stalls and households.',
        impactLevel: 'Medium',
        dailyVolume: '180 L/day',
      },
      {
        id: 'c-d3',
        name: `${bName} Daily Haat Demand Hub`,
        type: 'anchor_demand',
        distanceKm: 3.1,
        directionAngleDeg: 260,
        details: 'Strong weekly/daily market demand for fresh milk and curd packets.',
        impactLevel: 'High',
        dailyVolume: '450 L/day',
      },
    ],
    groceryCompetitors: [
      {
        id: 'c-g1',
        name: `${vName} Kirana & General Merchant`,
        type: 'competitor',
        distanceKm: 0.6,
        directionAngleDeg: 30,
        details: 'Established retail store with loyal neighbourhood customers.',
        impactLevel: 'High',
        dailyVolume: '₹18,000/day',
      },
      {
        id: 'c-g2',
        name: `${bName} Main Road Provision Store`,
        type: 'competitor',
        distanceKm: 2.4,
        directionAngleDeg: 190,
        details: 'Wholesale-cum-retail provision store with FMCG packaged goods.',
        impactLevel: 'Medium',
        dailyVolume: '₹35,000/day',
      },
    ],
    dairySpecificThreats: [
      {
        title: 'Green Fodder & Feed Price Volatility',
        severity: 'High',
        mitigation: 'Establish silage pit storage during harvest season and cultivate hybrid Napier grass on leased plot.',
      },
      {
        title: 'Summer Milk Yield Reduction (Heat Stress)',
        severity: 'Medium',
        mitigation: 'Install low-cost micro-foggers/sprinklers in shed and feed chilled clean water with mineral mixture.',
      },
    ],
    grocerySpecificThreats: [
      {
        title: 'Customer Credit Book (Khata) Delays',
        severity: 'High',
        mitigation: 'Enforce strict 7-day credit cap and introduce 2% prompt digital payment discount (UPI).',
      },
      {
        title: 'Perishable Spoilage in High Humidity',
        severity: 'Medium',
        mitigation: 'Install wire mesh ventilation racks and manage tight 3-day stock turns for perishables.',
      },
    ],
  };
}

